name: kisanapp
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.0







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  http: ^1.2.2
  intl_phone_number_input: ^0.7.4
  flutter_multi_formatter: ^2.13.0
  country_phone_code_picker: ^0.0.43
  flutter_screenutil: ^5.9.3
  flutter_responsive_framework: ^0.0.2
  auto_size_text: ^3.0.0
  csc_picker: ^0.2.7
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
