name: kisanapp
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.0







dependencies:
  auto_size_text: ^3.0.0
  country_picker_plus: ^2.0.2
  csc_picker: ^0.2.7
  dart_jsonwebtoken: ^2.14.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  phone_form_field: ^10.0.1
  pinput: ^5.0.0
  validators: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
